---
- name: graylog
  hosts: all
  become: yes
  become_method: sudo
  become_user: root
  remote_user: '{{admin_username}}'
  gather_facts: False
  pre_tasks:
   - name: 'install python'
     raw: 'sudo apt-get -y install python'


- name: graylog
  hosts: all
  become: yes
  become_method: sudo
  remote_user: '{{admin_username}}'
  become_user: root

  roles:
    - { role: common , tags: "common"} 
    - { role: graylog2, tags: "graylog2" }
    - { role: nginx, tags: "nginx" }
    
