---
- name: Prerequisites
  apt:
    name: [apt-transport-https, openjdk-8-jre-headless, uuid-runtime, pwgen]
    state: latest

- name: Install Elasticsearch -1
  shell: |
    wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -
    echo "deb https://artifacts.elastic.co/packages/oss-6.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-6.x.list

- name: Install Elasticsearch -2
  apt: 
    name: elasticsearch-oss 
    state: latest
    update-cache: yes

- name: change elasticsearch's configuration file
  template:
    src: elasticsearch.yml
    dest: /etc/elasticsearch/
    owner: root
    group: root
    mode: 0644

- name: start Elasticsearch
  service:
    name: elasticsearch
    state: started
    enabled: yes

- name: graylog -1
  apt:
    deb: "{{graylog_deb_url}}"

- name: graylog -2
  apt:
    name: graylog-server
    state: latest
    update_cache: yes

- name: Create graylog databases user
  mongodb_user:
    login_user: root
    login_password: '123456'
    login_database: admin
    database: graylog 
    name: graylog
    roles: readWrite
    password: '123456'
  
- name: Config Nginx
  copy:
    src: "{{ item }}"
    dest: /etc/nginx/conf.d/
  with_items:
    - default.conf
    - default.conf.graylog

- name: upload tip
  copy: 
    src: graylog.html
    dest: /data/wwwroot/

- name: upload script
  copy:
    src: config_domain.sh
    dest: /root/
    mode: 0750


- name: change configuration file
  template:
    src: server.conf
    dest: /etc/graylog/server/
    owner: root
    group: root
    mode: 0644

- name: start graylog2
  service:
    name: "{{ item }}" 
    state: restarted
    enabled: yes
  with_items:
    - graylog-server
    - nginx