---
# install Graylog by OS_family
- name: Install this role on {{ansible_os_family}}
  include: "{{ansible_os_family}}.yml"

# configure Graylog

- name: Copy graylog.html to server
  copy:
    src: graylog.html
    dest: /data/wwwroot
    owner: nginx
    group: nginx
    mode: '0640'

- name: Copy config_domain.sh to server and set X permission
  copy:
    src: config_domain.sh
    dest: /etc/graylog
    mode: '0740'

- name: Copy new default and backup old default
  template:
    src: default
    dest: /etc/nginx/conf.d/default.conf
    backup: yes

- name: change configuration file
  template:
    src: server.conf
    dest: /etc/graylog/server/
    owner: root
    group: root
    mode: 0644

- name: Start Graylog and restart Nginx
  service:
    name: "{{ item }}" 
    state: restarted
    enabled: yes
  loop:
    - graylog-server
    - nginx

# set soft link
- name: set soft link
  shell: |
    ln -sf /etc/graylog  /data/config
    ln -sf /var/log/graylog-server/server.log  /data/logs
    ln -sf /usr/share/graylog-server  /data/wwwroot/graylog-server
    ln -sf /usr/lib/systemd/system/graylog-server.service  /usr/lib/systemd/system/graylog.service

# Check version,
# must use sudo sh -c to solve the no-root permission
- block:
  - name: Check Graylog Version
    shell: sudo sh -c "echo' 1>> /data/logs/install_version.txt"

# check service state
- name: Check Graylog Service
  shell: systemctl status graylog | grep Active*
  register: check_graylog_service
  notify: check_graylog_service